---
all:
  children:
    controlplane:
      hosts:
        controlplane-1:
          ansible_host: 10.100.1.10
          vm_id: 1
        controlplane-2:
          ansible_host: 10.100.1.20
          vm_id: 2
        controlplane-3:
          ansible_host: 10.100.1.30
          vm_id: 3
      vars:
        ansible_user: root

    kubernetes:
      hosts:
        kubernetes-1:
          ansible_host: 10.100.1.40
          vm_id: 4
        kubernetes-2:
          ansible_host: 10.100.1.50
          vm_id: 5
      vars:
        ansible_user: root

    worker:
      hosts:
        worker-1:
          ansible_host: 10.100.1.60
          vm_id: 6
        worker-2:
          ansible_host: 10.100.1.70
          vm_id: 7
        worker-3:
          ansible_host: 10.100.1.80
          vm_id: 8
      vars:
        ansible_user: root

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
